# Generated by Django 2.2.11 on 2020-03-14 19:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='-', max_length=128)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='genre/icon')),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='-', max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studios',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime/image')),
                ('title', models.CharField(default='-', max_length=128)),
                ('native_title', models.CharField(default='-', max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('airing_date', models.DateTimeField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('total_episode', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='euphonime.Genre')),
            ],
            options={
                'db_table': 'anime',
            },
        ),
    ]
