# Generated by Django 2.2.11 on 2020-03-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Laki-laki'), (2, 'Perempuan')], null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='website',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
