# Generated by Django 2.2.11 on 2020-03-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0003_userreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReview',
            new_name='UserAnimeReview',
        ),
    ]
