# Generated by Django 2.2.11 on 2020-03-14 21:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0003_animeproducer_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime/image')),
                ('name', models.CharField(default='-', max_length=128)),
                ('native_name', models.CharField(default='-', max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'voice_acts',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime/image')),
                ('name', models.CharField(default='-', max_length=128)),
                ('native_name', models.CharField(default='-', max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='euphonime.Anime')),
                ('voice_act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='euphonime.VoiceAct')),
            ],
            options={
                'db_table': 'characters',
            },
        ),
    ]
