# Generated by Django 2.2.11 on 2020-03-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0004_auto_20200322_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='symbol',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
