# Generated by Django 2.2.11 on 2020-03-14 21:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0004_character_voiceact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OstAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='-', max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='genre/icon')),
            ],
            options={
                'db_table': 'ost_authors',
            },
        ),
        migrations.CreateModel(
            name='Ost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='-', max_length=128)),
                ('type', models.PositiveIntegerField(blank=True, choices=[(1, 'Opening Song'), (2, 'Ending Song'), (3, 'Insert Song')], null=True)),
                ('lyric', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='euphonime.Anime')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='euphonime.OstAuthor')),
            ],
            options={
                'db_table': 'ost',
            },
        ),
    ]
