# Generated by Django 2.2.11 on 2020-03-14 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0006_auto_20200314_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime/image')),
                ('title', models.CharField(default='-', max_length=128)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
