# Generated by Django 2.2.11 on 2020-03-14 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0007_auto_20200314_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranimescore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='euphonime.ProfileUser'),
        ),
        migrations.AlterField(
            model_name='userwatching',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='euphonime.ProfileUser'),
        ),
    ]
