# Generated by Django 2.2.11 on 2020-03-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0008_auto_20200314_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='description',
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Protagonis'), (2, 'Antagonis'), (3, 'Sampingan')], null=True),
        ),
    ]
