# Generated by Django 2.2.11 on 2020-03-15 01:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0009_auto_20200314_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ost',
            options={'verbose_name': 'Original Soundtrack'},
        ),
        migrations.AlterModelOptions(
            name='voiceact',
            options={'verbose_name': 'Voice Actress/Actor'},
        ),
        migrations.CreateModel(
            name='SampleVoiceAct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seiyuu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='euphonime.Genre')),
            ],
            options={
                'db_table': 'voice_act_samples',
            },
        ),
    ]
