# Generated by Django 2.2.11 on 2020-04-02 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0009_metageneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('meta_name', models.CharField(default='-', max_length=128)),
                ('page', models.CharField(blank=True, choices=[(1, 'Anime'), (2, 'Article'), (3, 'Character'), (4, 'Quote')], max_length=128, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meta_pages',
            },
        ),
    ]
