# Generated by Django 2.2.11 on 2020-03-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0011_auto_20200315_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplevoiceact',
            name='seiyuu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='euphonime.VoiceAct'),
        ),
    ]
