# Generated by Django 2.2.11 on 2020-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0011_auto_20200402_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metapage',
            name='page',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Anime'), (2, 'Article'), (3, 'Character'), (4, 'Quote')], null=True),
        ),
    ]
