# Generated by Django 2.2.11 on 2020-03-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0012_auto_20200315_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplevoiceact',
            name='name',
        ),
        migrations.AddField(
            model_name='samplevoiceact',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='samplevoiceact',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='seiyuu/audio'),
        ),
    ]
