# Generated by Django 2.2.11 on 2020-03-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0013_auto_20200315_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplevoiceact',
            old_name='url',
            new_name='audio',
        ),
    ]
