# Generated by Django 2.2.11 on 2020-04-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0014_auto_20200403_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='character',
            name='slug',
        ),
    ]
