# Generated by Django 2.2.11 on 2020-03-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0015_auto_20200315_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'TV'), (2, 'OVA'), (3, 'ONA'), (4, 'OAD'), (5, 'Movie')], null=True),
        ),
    ]
