# Generated by Django 2.2.11 on 2020-03-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0016_anime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
