# Generated by Django 2.2.11 on 2020-03-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0017_anime_mal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalAnime',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upload from MAL',
                'db_table': 'mal_anime',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='mal_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='voiceact',
            name='mal_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Main'), (2, 'Support')], null=True),
        ),
    ]
