# Generated by Django 2.2.11 on 2020-04-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0017_auto_20200403_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceact',
            name='slug',
            field=models.SlugField(blank=True, max_length=512, null=True),
        ),
    ]
