# Generated by Django 2.2.11 on 2020-03-15 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0018_auto_20200315_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='malanime',
            name='mal_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='malanime',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
