# Generated by Django 2.2.11 on 2020-03-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0019_auto_20200315_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to='anime/image'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to='character/image'),
        ),
        migrations.AlterField(
            model_name='voiceact',
            name='image',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to='seiyuu/image'),
        ),
    ]
