# Generated by Django 2.2.11 on 2020-03-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0020_auto_20200315_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='voiceact',
            name='image_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
