# Generated by Django 2.2.11 on 2020-03-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0021_auto_20200315_0447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malanime',
            options={'verbose_name': 'Sync from MAL'},
        ),
        migrations.AddField(
            model_name='malanime',
            name='log',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
