# Generated by Django 2.2.11 on 2020-03-15 16:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0022_auto_20200315_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='euphonime.Anime'),
        ),
    ]
