# Generated by Django 2.2.11 on 2020-03-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0023_auto_20200315_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceact',
            name='native_name',
        ),
        migrations.AddField(
            model_name='voiceact',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceact',
            name='family_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='voiceact',
            name='given_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
