# Generated by Django 2.2.11 on 2020-03-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0028_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='anime',
        ),
    ]
