# Generated by Django 2.2.11 on 2020-03-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0035_auto_20200317_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpolls',
            old_name='score',
            new_name='poll',
        ),
    ]
