# Generated by Django 2.2.11 on 2020-03-18 00:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0038_auto_20200318_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceact',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
