# Generated by Django 2.2.11 on 2020-03-18 03:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0039_auto_20200318_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
