# Generated by Django 2.2.11 on 2020-03-19 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0040_auto_20200318_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='euphonime.Anime')),
            ],
            options={
                'db_table': 'anime_characters',
            },
        ),
    ]
