# Generated by Django 2.2.11 on 2020-03-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0041_animecharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='animecharacter',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='euphonime.Character'),
        ),
    ]
