# Generated by Django 2.2.11 on 2020-03-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphonime', '0042_animecharacter_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='anime',
        ),
    ]
